# fly.toml app configuration file generated for deno-flyio on 2023-09-13T11:55:56-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "deno-flyio3"
primary_region = "dfw"

[build]

[env]
  PORT = "8000"

[processes]
  app = "run -A --unstable ./server.tsx"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
